name: Sync Bitbucket to GitLab

on:
  workflow_dispatch:  # Permet de déclencher l'action manuellement

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository from Bitbucket
        run: |
          git clone https://x-token-auth:ATCTT3xFfGN0VrVFWn7LVYgpCtRl-UApLFzlNcdtwldiaTEDLEd7qv2OeuKvTNk8oiWOagNJklvE3GXMJQHx-o6jLdXInE_HtR5Blz2IebDO7aCaXSsAkE6g7DKFG53uJ4OiKzxDiAL8TH5h_P7gVasMhxTs5nZ8zdeG8JCZDm3kLAi5ZPy_tMc=FE15E912@bitbucket.org/agartev/atlas.git repo

      - name: Set Up GitLab Remote
        run: |
          cd repo
          git remote add gitlab https://xtoken-auth:glpat-ydFXhDi1FqeyG5DjAb7V@gitlab.com/Agartev/atlas.git

      - name: Check if GitLab Repository is Empty
        id: check_empty
        run: |
          cd repo
          # Vérifier si le dépôt GitLab est vide
          if [ "$(git ls-remote --heads gitlab main)" ]; then
            echo "GitLab repository is not empty."
            echo "empty=false" >> $GITHUB_ENV
          else
            echo "GitLab repository is empty."
            echo "empty=true" >> $GITHUB_ENV
          fi

      - name: Push to GitLab if Not Empty
        if: env.empty == 'false'
        run: |
          cd repo
          # Pousser les modifications vers GitLab si le dépôt n'est pas vide
          git push gitlab main

      - name: Initialize and Push to GitLab if Empty
        if: env.empty == 'true'
        run: |
          cd repo
          # Initialiser le dépôt GitLab s'il est vide et pousser les fichiers
          git checkout -b main
          git add .
          git commit -m "Initial commit"
          git push gitlab main
